name: mybackend_lastversion
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  firebase_dart: ^1.1.2
  http: ^1.2.0
  orm: ^4.0.0-beta
  path: ^1.9.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
